Vagrant.configure('2') do |config|

  config.vm.box = "labkey/development"

  config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 4096
      vbox.cpus = 2
      vbox.gui = false
  end

  config.vm.define "labkey" do |labkey|
    labkey.vm.hostname = "labkey.vm"
    #labkey.vm.network "public_network"
    labkey.vm.provision "shell", privileged:true, inline: "/vagrant/setup"
  end

end
