#!/bin/bash

# APTCACHER if you have it
if [ -f "/vagrant/02proxy" ]; then
  cp /vagrant/02proxy /etc/apt/apt.conf.d/02proxy
fi

# install 'system' software

apt-get update --yes
apt-get install --yes apt-transport-https ca-certificates curl software-properties-common

# docker repository
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# oracle java repository
add-apt-repository ppa:webupd8team/java
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

# TODO cran repository

apt-get update --yes
apt-get upgrade --yes
# TODO docker-ce did not work???
# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/
# apt-get remove --yes docker docker-engine docker.io
apt-get install --yes direnv docker.io git graphviz myrepos npm oracle-java8-installer pandoc postgresql r-base-core subversion tree
#VBoxClient-all
snap install intellij-idea-ultimate --classic
