Vagrant.configure('2') do |config|

  config.vm.box = "fso/artful64-desktop"
  #config.vm.box = "bento/ubuntu-16.04"
  #config.vm.box = "bento/ubuntu-17.10"

  config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 4096
      vbox.cpus = 2
      vbox.gui = false
  end

  config.vm.define "labkey" do |labkey|
    labkey.vm.hostname = "labkey.vm"
    #labkey.vm.network "public_network"
    labkey.vm.provision "shell", privileged:true, inline: "/vagrant/setup"
  end

end
