#!/bin/bash

export LABKEYDIR=/home/vagrant/labkey
export SVNBRANCH=trunk
export GITBRANCH=develop
export SVNUSER=cpas
export SVNPASSWORD=cpas
export USERGROUP=$(id -un):$(id -gn)

if [ -f /vagrant/setenv ]; then
  . /vagrant/setenv
fi


# user and credential set up

echo "https://$GITUSER:$GITPASSWORD@github.com" > ~/.git-credentials
chmod 0600 ~/.git-credentials
git config --global credential.helper store


# jetbrains idea

mkdir -p ~/bin
printf '#!/bin/bash\n/snap/intellij-idea-ultimate/3/bin/idea.sh $* &\n' > ~/bin/idea
chmod +x ~/bin/idea
mkdir -p ~/.local/share/applications/
if [ -f ~/.gnome/apps/jetbrains-idea.desktop ]; then cp ~/.gnome/apps/jetbrains-idea.desktop ~/.local/share/applications/; fi


# enlist 

mkdir -p $LABKEYDIR
sudo chown $USERGROUP $LABKEYDIR

if [ ! -d "$LABKEYDIR/$SVNBRANCH" ]; then
  mkdir -p $LABKEYDIR/$SVNBRANCH
  cd $LABKEYDIR/$SVNBRANCH

  if [ "$SVNBRANCH" = "trunk" ]; then
    svn checkout --username $SVNUSER --password $SVNPASSWORD https://hedgehog.fhcrc.org/tor/stedi/$SVNBRANCH $LABKEYDIR/$SVNBRANCH
  else
    svn checkout --username $SVNUSER --password $SVNPASSWORD https://hedgehog.fhcrc.org/tor/stedi/branches/$SVNBRANCH $LABKEYDIR/$SVNBRANCH
  fi
  
  # fix up classpaths in run configurations (consider: complicated sed command?)
  cp /vagrant/runConfigurations/* $LABKEYDIR/$SVNBRANCH/.idea/runConfigurations
else
  cd $LABKEYDIR/$SVNBRANCH
  svn update --username $SVNUSER --password $SVNPASSWORD
fi

# tomcat 

pushd /vagrant
export TOMCAT_ZIP=$(ls apache-tomcat*.zip)
export TOMCAT=$(basename $TOMCAT_ZIP .zip)
popd

if [ ! -d  "$LABKEYDIR/$SVNBRANCH/$TOMCAT" ]; then
  unzip /vagrant/$TOMCAT_ZIP
  echo "systemProp.tomcat.home=$LABKEYDIR/$SVNBRANCH/$TOMCAT" >> gradle.properties
fi

cd $LABKEYDIR/$SVNBRANCH
echo "org.gradle.parallel=true" >> gradle.properties
echo "deployMode=dev" >> gradle.properties



echo 'PATH_add $(pwd)' > .envrc
echo 'export JAVA_HOME=/usr/lib/jvm/java-8-oracle' >> .envrc
echo "export CATALINA_HOME=$(pwd)/$TOMCAT" >> .envrc
direnv allow .

echo ./gradlew :server:test:uiTest -Psuite=DRT >> drt
echo ./gradlew :server:test:uiTest -Psuite=BVT >> bvt
chmod +x drt bvt

# database

sudo su postgres -c "psql -c \"ALTER USER postgres PASSWORD 'sasa'\""

# intellij

mkdir -p /home/vagrant/.IntelliJIdea2017.2/config/options
printf "<application>\n<component name=\"PathMacrosImpl\">\n<macro name=\"CATALINA_HOME\" value=\"$LABKEYDIR/$SVNBRANCH/$TOMCAT\" />\n</component>\n</application>" > /home/vagrant/.IntelliJIdea2017.2/config/options/path.macros.xml
cp /vagrant/jdk.table.xml ~/.IntelliJIdea2017.2/config/options


# tests require firefox 45 (I know, this is bad)

mkdir -p /home/vagrant/Desktop
pushd /home/vagrant/Desktop
tar xjf /vagrant/firefox-45.0.tar.bz2
mv firefox firefox45
# set up test to use firefox45
cp /vagrant/test.properties $LABKEYDIR/$SVNBRANCH/server/test
popd

# user environment

cd /home/vagrant

# set firefox home directory
mkdir -p .mozilla/firefox/vagrant.default
cp /vagrant/mozilla/firefox/profiles.ini .mozilla/firefox/profiles.ini
cp /vagrant/mozilla/firefox/vagrant.default/prefs.js .mozilla/firefox/vagrant.default/prefs.js
# set idea to start on login
if [ -f "/home/vagrant/.local/share/applications/jetbrains-idea.desktop" ]; then
  cp ~/.local/share/applications/jetbrains-idea.desktop ~/.config/autostart/
fi

# set JAVA_HOME 
echo 'export JAVA_HOME=/usr/lib/jvm/java-8-oracle' >> ~/.envrc
direnv allow .
# enable direnv program
echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
# set favorites (gnome panel shortcuts)
mkdir -p ~/.local/share/applications/
printf "[Desktop Entry]\nVersion=1.0\nType=Application\nName=IntelliJ IDEA\nIcon=/snap/intellij-idea-ultimate/3/bin/idea.png\nExec="/snap/intellij-idea-ultimate/3/bin/idea.sh" %f\nComment=The Drive to Develop\nCategories=Development;IDE;\nTerminal=false\nStartupWMClass=jetbrains-idea\n" >  ~/.local/share/applications/jetbrains-idea.desktop
dbus-launch gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'firefox.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.gedit.desktop', 'gnome-calculator.desktop', 'jetbrains-idea.desktop']"

echo "alias g='gradlew'" >> ~/.bash_aliases

mkdir -p /home/vagrant/Desktop
pandoc -s /vagrant/README.md -o /home/vagrant/Desktop/README.html


#  pre-build 

cd $LABKEYDIR/$SVNBRANCH
./gradlew dependencies copyExternalLibs
./gradlew pickPg

sync
